### ISSUE TITLE
Issues with cargo test --doc

### ISSUE THREAD

**Issue by mikemadden42** [CrowdStrike/rusty-falcon#99]
`cargo test --doc` is currently failing even after I set the correct environment variables.
- FALCON_CLIENT_ID
- FALCON_CLIENT_SECRET
- FALCON_CLOUD

```
$ cargo test --doc
    Finished test [unoptimized + debuginfo] target(s) in 0.30s
   Doc-tests rusty_falcon
error: doctest failed, to rerun pass `--doc`

running 1 test
test src/lib.rs - (line 17) ... FAILED

failures:

---- src/lib.rs - (line 17) stdout ----
Test executable failed (exit status: 101).

stderr:
thread 'main' panicked at 'Could not fetch CCID: Serde(Error("missing field `errors`", line: 10, column: 1))', src/lib.rs:17:10
stack backtrace:
   0:        0x10e75f933 - std::backtrace_rs::backtrace::libunwind::trace::h3a0c717b60f51a7a
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x10e75f933 - std::backtrace_rs::backtrace::trace_unsynchronized::h9335432fefe8ab97
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10e75f933 - std::sys_common::backtrace::_print_fmt::hd4969dd20679c9f5
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x10e75f933 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h574028a0687b01b1
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x10e77beeb - core::fmt::rt::Argument::fmt::h55a6886216a743b4
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/fmt/rt.rs:138:9
   5:        0x10e77beeb - core::fmt::write::hc3a291ca045d4386
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/fmt/mod.rs:1094:21
   6:        0x10e75cac8 - std::io::Write::write_fmt::hce33c3aef899c477
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/io/mod.rs:1713:15
   7:        0x10e75f72a - std::sys_common::backtrace::_print::h9cb3bdde0b8af541
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:47:5
   8:        0x10e75f72a - std::sys_common::backtrace::print::hec404ce64d885bc1
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:34:9
   9:        0x10e760b75 - std::panicking::default_hook::{{closure}}::hb702376be934f723
  10:        0x10e76097f - std::panicking::default_hook::he55b66a35bee68d8
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:288:9
  11:        0x10e761013 - std::panicking::rust_panic_with_hook::hcabbae61abda3f7a
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:705:13
  12:        0x10e760f33 - std::panicking::begin_panic_handler::{{closure}}::hb0d2e10207b82ddc
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:597:13
  13:        0x10e75fd39 - std::sys_common::backtrace::__rust_end_short_backtrace::h3fbd78d34f010841
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:151:18
  14:        0x10e760c6d - rust_begin_unwind
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
  15:        0x10e78e1e3 - core::panicking::panic_fmt::heecc6c3994a0556d
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
  16:        0x10e78e755 - core::result::unwrap_failed::he284362399a4b885
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/result.rs:1651:5
  17:        0x10e321c81 - core::result::Result<T,E>::expect::h6988c4d6483e24e7
  18:        0x10e3445ae - rust_out::main::{{closure}}::hc76dc9bec3b023d4
  19:        0x10e32c58a - tokio::runtime::park::CachedParkThread::block_on::{{closure}}::h1b2760a7e0054c28
  20:        0x10e32c0c8 - tokio::runtime::park::CachedParkThread::block_on::h726187ef8dd40a9b
  21:        0x10e32d25d - tokio::runtime::context::blocking::BlockingRegionGuard::block_on::ha72e2bf2a68ce3fd
  22:        0x10e32d4cc - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}::hd85d2ff7e5874311
  23:        0x10e32cbdc - tokio::runtime::context::runtime::enter_runtime::h43e5a788f8dbd7a9
  24:        0x10e32d483 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h6eea013df391ffc9
  25:        0x10e32d3cc - tokio::runtime::runtime::Runtime::block_on::h857b6a2d1a5c9379
  26:        0x10e3441cc - rust_out::main::h9d98ab4a1af73092
  27:        0x10e31b30a - core::ops::function::FnOnce::call_once::h6a547782d2640425
  28:        0x10e319af9 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf723d7d76e2e3334
  29:        0x10e319c90 - std::rt::lang_start::{{closure}}::hf7417e6019bfa6cb
  30:        0x10e75974a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h96d127ef97eff83f
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:284:13
  31:        0x10e75974a - std::panicking::try::do_call::h750f65c5552cbedc
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:500:40
  32:        0x10e75974a - std::panicking::try::h134876d5b1751dfb
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:464:19
  33:        0x10e75974a - std::panic::catch_unwind::hb95304deb3bb285f
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panic.rs:142:14
  34:        0x10e75974a - std::rt::lang_start_internal::{{closure}}::hd09b5eab6ceb98ae
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/rt.rs:148:48
  35:        0x10e75974a - std::panicking::try::do_call::h626dca2603238bd2
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:500:40
  36:        0x10e75974a - std::panicking::try::h8cd8d695bf520cd3
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:464:19
  37:        0x10e75974a - std::panic::catch_unwind::hf8ce2d2f85ad4f6d
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panic.rs:142:14
  38:        0x10e75974a - std::rt::lang_start_internal::h35bfd4814712c868
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/rt.rs:148:20
  39:        0x10e319c68 - std::rt::lang_start::h0d9bac5a00668aa8
  40:        0x10e344768 - _main



failures:
    src/lib.rs - (line 17)

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.64s
```

**Comment by mikemadden42** [comment]
With the recent updates to the main branch, these errors are fixed.

```
$ cargo test --doc
    Finished test [unoptimized + debuginfo] target(s) in 0.30s
   Doc-tests rusty_falcon

running 1 test
test src/lib.rs - (line 17) ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.56s
```
